#!/usr/bin/env bash

# Arguments of git-fix are arguments to git-commit

function echo_f {
  tput setaf $1
  shift
  echo -n "$*"
  tput sgr0
  echo
}

function log {
  echo_f 12 ">> $*"
}

function report_commit {
  git show --shortstat --pretty=format:'%C(yellow)%h %C(cyan)%cn %C(blue)%cr%C(reset) %s %C(red)%d' $1
}

git commit --quiet --amend --no-edit "$@"
if [[ $? -ne 0 ]]; then
  echo_f 1 'git-fix: Failed to commit'
  exit 1
fi

log 'Amend this commit'
report_commit 'HEAD@{1}'

log 'Into this commit'
report_commit 'HEAD'

log 'Diff'
git diff --stat 'HEAD@{1}' 'HEAD'
