#!/usr/bin/env bash

# Looks like you cannot have relative paths with diff --stat

# The default (no args) is to compare the working tree to the index,
# repeating 'git diff' semantics

if [[ $# -eq 0 ]]; then
  git diff --stat
elif [[ $1 = '-h' ]] || [[ $1 = '--help' ]] || [[ $1 = 'help' ]]; then
  git help diff
else
  git diff --stat "$@"
fi


