#!/usr/bin/env bash

# The default (no args) is to compare the working tree to the index,
# repeating 'git diff' semantics

if [[ $# -eq 0 ]]; then
  git difftool
elif [[ $1 = '-h' ]] || [[ $1 = '--help' ]] || [[ $1 = 'help' ]]; then
  git help difftool
else
  git difftool "$@"
fi
